_prefs: 
  mapid: openroads.f5b2879a
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 123.6803
  - 10.1739
  - 12
description: OpenRoads - Municipal boundaries for the Philippines
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 12
minzoom: 6
name: OR - municipal boundaries
source: "mapbox:///openroads.6e355424"
styles: 
  - style.mss
template: ''
